TOPIC: "some_topic"
CONSUMER_GROUP: "frontend"
NAMESPACE: "some_eventhub_namespace.servicebus.anazurecloud.net"
SHARED_ACCESS_POLICY: "message-auth-rule"
BUFFER_SIZE: 50
LOG_LEVEL: "DEBUG"
DB_HOST: "dbs-dev-data.postgres.database.anazurecloud.net"
#DB_HOST: "docker.for.mac.host.internal"
DB_PORT: "5432"
DB_USER: "someuser@dbs-dev-data.postgres.database.anazurecloud.net"
DB_DATABASE: "grafana"
DB_SCHEMA: "public"

