TOPIC: "lte_message"
CONSUMER_GROUP: "frontend"
NAMESPACE: "fetest-dev-mqtt-eventhubs-namespace.servicebus.usgovcloudapi.net"
SHARED_ACCESS_POLICY: "lte_message-auth-rule"
BUFFER_SIZE: 50
LOG_LEVEL: "DEBUG"
DB_HOST: "dbs-fetest-dev-data.postgres.database.usgovcloudapi.net"
#DB_HOST: "docker.for.mac.host.internal"
DB_PORT: "5432"
DB_USER: "postgres@dbs-fetest-dev-data.postgres.database.usgovcloudapi.net"
DB_DATABASE: "grafana"
DB_SCHEMA: "public"

